#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays this
# data in a list format ordered from the greatest to the lowest number of
# occurrences.

awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $2, $3, $1}'
