#!/usr/bin/env bash

# This script is displaying "Best School" 10 times

# Initialize a counter
counter=0

# Use a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]
do
	echo "Best School"
	#increment the counter
	((counter++))
done
